#!/usr/bin/env node
/**
 * Renders products/degent/deploy/.env.{signet,mainnet}.example from the service's env.schema.json and
 * compose-vars.json (deployment knobs). The schema is the source of truth; never edit the examples by hand.
 *
 *   node products/degent/deploy/gen-env.mjs           # (re)write both files
 *   node products/degent/deploy/gen-env.mjs --check   # exit 1 if they are stale (test/deploy.test.ts runs the same check)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const here = fileURLToPath(new URL('.', import.meta.url));
const schemaPath = new URL('../services/mint/env.schema.json', import.meta.url);
export const ENVIRONMENTS = ['signet', 'mainnet'];

export function load() {
  const schema = JSON.parse(readFileSync(schemaPath, 'utf8'));
  const vars = JSON.parse(readFileSync(new URL('./compose-vars.json', import.meta.url), 'utf8'));
  return { schema, vars };
}

const isFileTwin = (p) => Boolean(p['x-secret-file-for']);

/** Secret variables: name, secret file name (last segment of the SOPS path) and SOPS path. */
export function secretVars(schema = load().schema) {
  return Object.entries(schema.properties)
    .filter(([, p]) => p['x-secret'])
    .map(([name, p]) => ({ name, file: p['x-secret'].split('/').pop(), sops: p['x-secret'], required: Boolean(p['x-required-unless-regtest']) }));
}

/** Service variables the operator sets through the .env file (everything not fixed by compose and not secret). */
export function passthroughVars({ schema, vars } = load()) {
  return Object.entries(schema.properties)
    .filter(([name, p]) => !(name in vars.fixed) && !p['x-secret'] && !isFileTwin(p))
    .map(([name]) => name);
}

/** Required on a non-regtest network: the schema's `required` plus x-required-unless-regtest. */
export function requiredOffRegtest(schema = load().schema) {
  return Object.entries(schema.properties)
    .filter(([name, p]) => schema.required.includes(name) || p['x-required-unless-regtest'])
    .map(([name]) => name);
}

/** Word-wrap a description into `# ` comment lines of at most ~110 columns. */
const comment = (text) => {
  const lines = [];
  let line = '#';
  for (const w of text.split(/\s+/)) {
    if (line.length + w.length + 1 > 110 && line !== '#') {
      lines.push(line);
      line = '#';
    }
    line += ` ${w}`;
  }
  lines.push(line);
  return lines.join('\n');
};

export function renderEnvExample(env, { schema, vars } = load()) {
  const ex = vars.examples[env] ?? {};
  const required = new Set(requiredOffRegtest(schema));
  const out = [];
  out.push(
    `# GENERATED by products/degent/deploy/gen-env.mjs from products/degent/services/mint/env.schema.json and`,
    `# products/degent/deploy/compose-vars.json. Do not edit: change those, then run the generator.`,
    `#`,
    `#   cp .env.${env}.example .env.${env}   # fill in every empty REQUIRED value`,
    `#   docker compose -f compose.${env}.yaml --env-file .env.${env} up -d --build`,
    `#`,
    `# No secret values in this file: secrets are files in $SECRETS_DIR (listed below).`,
    '',
    '# ============================================================ degent-mint service (env.schema.json)',
  );
  for (const name of passthroughVars({ schema, vars })) {
    const p = schema.properties[name];
    const req = required.has(name);
    const example = Object.hasOwn(ex, name) ? ex[name] : undefined;
    out.push('');
    if (p.description) out.push(comment(p.description));
    if (p.enum) out.push(`# One of: ${p.enum.join(', ')}.`);
    if (req) out.push(`# REQUIRED on ${env}.`);
    else if (example === null) out.push(`# Set it for ${env} (no safe default).`);
    if (req || example !== undefined) out.push(`${name}=${example ?? ''}`);
    else out.push(`# ${name}=${p.default ?? ''}`);
  }
  out.push('', '# ============================================================ secrets (files, never values here)');
  out.push(`# One file per secret in $SECRETS_DIR, readable by uid 1000 only. Suggested SOPS paths in parentheses.`);
  for (const s of secretVars(schema)) {
    if (s.name === 'PARENT_KEY_FILE' && env === 'mainnet') {
      out.push(`#   ${s.name}: not used on mainnet (the parent key lives in the KMS signer; the service refuses a key file)`);
      continue;
    }
    const need = s.required || (s.name === 'PARENT_KEY_FILE' && env !== 'mainnet') ? 'REQUIRED' : 'optional: empty file = unset';
    out.push(`#   ${s.name}  <- $SECRETS_DIR/${s.file}  (${s.sops})  [${need}]`);
  }
  out.push('', '# ============================================================ deployment (compose-vars.json)');
  for (const [name, d] of Object.entries(vars.deploy)) {
    const v = Object.hasOwn(d, env) ? d[env] : d.default;
    out.push('', comment(d.description));
    if (v === null) out.push(`# REQUIRED on ${env}.`, `${name}=`);
    else out.push(`${name}=${v}`);
  }
  return `${out.join('\n')}\n`;
}

export const examplePath = (env) => `${here}.env.${env}.example`;

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const check = process.argv.includes('--check');
  let stale = 0;
  for (const env of ENVIRONMENTS) {
    const want = renderEnvExample(env);
    let have = '';
    try {
      have = readFileSync(examplePath(env), 'utf8');
    } catch {}
    if (have === want) continue;
    if (check) {
      console.error(`stale: ${examplePath(env)} (run node products/degent/deploy/gen-env.mjs)`);
      stale++;
    } else {
      writeFileSync(examplePath(env), want);
      console.log(`wrote ${examplePath(env)}`);
    }
  }
  process.exit(stale ? 1 : 0);
}
